services:
  - type: web
    name: situational-room
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /status
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: CESIUM_TOKEN
        sync: false
      - key: ADSBX_KEY
        sync: false
      - key: DATALASTIC_KEY
        sync: false
      - key: SITE_USERNAME
        sync: false
      - key: SITE_PASSWORD
        sync: false
